class SlimXError(Exception): ...
class ProviderError(SlimXError): ...
class ProviderAuthError(ProviderError): ...
class ProviderRateLimitError(ProviderError): ...
class ProviderTimeoutError(ProviderError): ...
class ToolExecutionError(SlimXError): ...
class SchemaError(SlimXError): ...
